# Generated by Django 6.1 on 2026-08-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
